name: micro-kick
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.20
  - pip>=20.3.3
  - matplotlib>=3.3.3
  - astropy
  - gala
  - scipy
  - jupyter
  - jupyterlab
  - ipython
  - seaborn
  - nbstripout